import net.sf.gilead.pojo.gwt.LightEntity;

/**
${pojo.getClassJavaDoc(pojo.getDeclarationName() + " generated by hbm2java", 0)}.
 *
 * Custom pojo generation.
 *
 * @author Denis Jacquet
 *
 */
<#include "Ejb3TypeDeclaration.ftl"/>
${pojo.getClassModifiers()} ${pojo.getDeclarationType()} ${pojo.getDeclarationName()} extends LightEntity ${pojo.getExtendsDeclaration()} ${pojo.getImplementsDeclaration()}