package com.karrus.demo.shared.hibernate;
// Generated 14 janv. 2020 17:44:50 by Hibernate Tools 5.4.7.Final

/**
 * BtBoxId generated by hbm2java
 */
public class BtBoxId implements java.io.Serializable {

	private String site;
	private String serial;

	public BtBoxId() {
	}

	public BtBoxId(String site, String serial) {
		this.site = site;
		this.serial = serial;
	}

	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	public String getSerial() {
		return this.serial;
	}

	public void setSerial(String serial) {
		this.serial = serial;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BtBoxId))
			return false;
		BtBoxId castOther = (BtBoxId) other;

		return ((this.getSite() == castOther.getSite()) || (this.getSite() != null && castOther.getSite() != null
				&& this.getSite().equals(castOther.getSite())))
				&& ((this.getSerial() == castOther.getSerial()) || (this.getSerial() != null
						&& castOther.getSerial() != null && this.getSerial().equals(castOther.getSerial())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSite() == null ? 0 : this.getSite().hashCode());
		result = 37 * result + (getSerial() == null ? 0 : this.getSerial().hashCode());
		return result;
	}

}
