package com.karrus.demo.shared.hibernate;
// Generated 14 janv. 2020 17:44:50 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * BtIttArchiveId generated by hbm2java
 */
public class BtIttArchiveId implements java.io.Serializable {

	private Date timestamp;
	private String origin;
	private String destination;
	private String macSecret;
	private String class_;
	private Boolean attValid;
	private Integer travelTime;

	public BtIttArchiveId() {
	}

	public BtIttArchiveId(Date timestamp, String origin, String destination, String macSecret, String class_,
			Boolean attValid, Integer travelTime) {
		this.timestamp = timestamp;
		this.origin = origin;
		this.destination = destination;
		this.macSecret = macSecret;
		this.class_ = class_;
		this.attValid = attValid;
		this.travelTime = travelTime;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	public String getMacSecret() {
		return this.macSecret;
	}

	public void setMacSecret(String macSecret) {
		this.macSecret = macSecret;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public Boolean getAttValid() {
		return this.attValid;
	}

	public void setAttValid(Boolean attValid) {
		this.attValid = attValid;
	}

	public Integer getTravelTime() {
		return this.travelTime;
	}

	public void setTravelTime(Integer travelTime) {
		this.travelTime = travelTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BtIttArchiveId))
			return false;
		BtIttArchiveId castOther = (BtIttArchiveId) other;

		return ((this.getTimestamp() == castOther.getTimestamp()) || (this.getTimestamp() != null
				&& castOther.getTimestamp() != null && this.getTimestamp().equals(castOther.getTimestamp())))
				&& ((this.getOrigin() == castOther.getOrigin()) || (this.getOrigin() != null
						&& castOther.getOrigin() != null && this.getOrigin().equals(castOther.getOrigin())))
				&& ((this.getDestination() == castOther.getDestination())
						|| (this.getDestination() != null && castOther.getDestination() != null
								&& this.getDestination().equals(castOther.getDestination())))
				&& ((this.getMacSecret() == castOther.getMacSecret()) || (this.getMacSecret() != null
						&& castOther.getMacSecret() != null && this.getMacSecret().equals(castOther.getMacSecret())))
				&& ((this.getClass_() == castOther.getClass_()) || (this.getClass_() != null
						&& castOther.getClass_() != null && this.getClass_().equals(castOther.getClass_())))
				&& ((this.getAttValid() == castOther.getAttValid()) || (this.getAttValid() != null
						&& castOther.getAttValid() != null && this.getAttValid().equals(castOther.getAttValid())))
				&& ((this.getTravelTime() == castOther.getTravelTime())
						|| (this.getTravelTime() != null && castOther.getTravelTime() != null
								&& this.getTravelTime().equals(castOther.getTravelTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTimestamp() == null ? 0 : this.getTimestamp().hashCode());
		result = 37 * result + (getOrigin() == null ? 0 : this.getOrigin().hashCode());
		result = 37 * result + (getDestination() == null ? 0 : this.getDestination().hashCode());
		result = 37 * result + (getMacSecret() == null ? 0 : this.getMacSecret().hashCode());
		result = 37 * result + (getClass_() == null ? 0 : this.getClass_().hashCode());
		result = 37 * result + (getAttValid() == null ? 0 : this.getAttValid().hashCode());
		result = 37 * result + (getTravelTime() == null ? 0 : this.getTravelTime().hashCode());
		return result;
	}

}
