package com.karrus.demo.shared.hibernate;
// Generated 14 janv. 2020 17:44:50 by Hibernate Tools 5.4.7.Final

/**
 * BtIttArchive generated by hbm2java
 */
public class BtIttArchive implements java.io.Serializable {

	private BtIttArchiveId id;

	public BtIttArchive() {
	}

	public BtIttArchive(BtIttArchiveId id) {
		this.id = id;
	}

	public BtIttArchiveId getId() {
		return this.id;
	}

	public void setId(BtIttArchiveId id) {
		this.id = id;
	}

}
