package com.karrus.demo.shared.hibernate;
// Generated 14 janv. 2020 17:44:50 by Hibernate Tools 5.4.7.Final

/**
 * BtItt generated by hbm2java
 */
public class BtItt implements java.io.Serializable {

	private BtIttId id;
	private String origin;
	private String destination;
	private String class_;
	private boolean attValid;

	public BtItt() {
	}

	public BtItt(BtIttId id, String origin, String destination, boolean attValid) {
		this.id = id;
		this.origin = origin;
		this.destination = destination;
		this.attValid = attValid;
	}

	public BtItt(BtIttId id, String origin, String destination, String class_, boolean attValid) {
		this.id = id;
		this.origin = origin;
		this.destination = destination;
		this.class_ = class_;
		this.attValid = attValid;
	}

	public BtIttId getId() {
		return this.id;
	}

	public void setId(BtIttId id) {
		this.id = id;
	}

	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public boolean isAttValid() {
		return this.attValid;
	}

	public void setAttValid(boolean attValid) {
		this.attValid = attValid;
	}

}
