package com.karrus.demo.shared.hibernate;
// Generated 14 janv. 2020 17:44:50 by Hibernate Tools 5.4.7.Final

/**
 * CtCountData1min generated by hbm2java
 */
public class CtCountData1min implements java.io.Serializable {

	private CtCountData1minId id;

	public CtCountData1min() {
	}

	public CtCountData1min(CtCountData1minId id) {
		this.id = id;
	}

	public CtCountData1minId getId() {
		return this.id;
	}

	public void setId(CtCountData1minId id) {
		this.id = id;
	}

}
