package com.karrus.demo.shared.hibernate;
// Generated 14 janv. 2020 17:44:50 by Hibernate Tools 5.4.7.Final

/**
 * CtCountData1h generated by hbm2java
 */
public class CtCountData1h implements java.io.Serializable {

	private CtCountData1hId id;

	public CtCountData1h() {
	}

	public CtCountData1h(CtCountData1hId id) {
		this.id = id;
	}

	public CtCountData1hId getId() {
		return this.id;
	}

	public void setId(CtCountData1hId id) {
		this.id = id;
	}

}
