package com.karrus.demo.shared.hibernate;
// Generated 14 janv. 2020 17:30:47 by Hibernate Tools 5.4.7.Final

/**
 * CtCountData generated by hbm2java
 */
public class CtCountData implements java.io.Serializable {

	private CtCountDataId id;
	private Double occupancy;
	private Integer count;
	private Double speed;
	private Integer latency;

	public CtCountData() {
	}

	public CtCountData(CtCountDataId id) {
		this.id = id;
	}

	public CtCountData(CtCountDataId id, Double occupancy, Integer count, Double speed, Integer latency) {
		this.id = id;
		this.occupancy = occupancy;
		this.count = count;
		this.speed = speed;
		this.latency = latency;
	}

	public CtCountDataId getId() {
		return this.id;
	}

	public void setId(CtCountDataId id) {
		this.id = id;
	}

	public Double getOccupancy() {
		return this.occupancy;
	}

	public void setOccupancy(Double occupancy) {
		this.occupancy = occupancy;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Double getSpeed() {
		return this.speed;
	}

	public void setSpeed(Double speed) {
		this.speed = speed;
	}

	public Integer getLatency() {
		return this.latency;
	}

	public void setLatency(Integer latency) {
		this.latency = latency;
	}

}
