package com.karrus.demo.shared.hibernate;
// Generated 14 janv. 2020 17:44:50 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * DiagRp generated by hbm2java
 */
public class DiagRp implements java.io.Serializable {

	private String id;
	private Date timestamp;
	private String station;
	private Double batteryLevel;
	private Double rssiAverage;
	private Double rssiStd;
	private Double lqiAverage;
	private Double lqiStd;

	public DiagRp() {
	}

	public DiagRp(String id, String station) {
		this.id = id;
		this.station = station;
	}

	public DiagRp(String id, String station, Double batteryLevel, Double rssiAverage, Double rssiStd, Double lqiAverage,
			Double lqiStd) {
		this.id = id;
		this.station = station;
		this.batteryLevel = batteryLevel;
		this.rssiAverage = rssiAverage;
		this.rssiStd = rssiStd;
		this.lqiAverage = lqiAverage;
		this.lqiStd = lqiStd;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public String getStation() {
		return this.station;
	}

	public void setStation(String station) {
		this.station = station;
	}

	public Double getBatteryLevel() {
		return this.batteryLevel;
	}

	public void setBatteryLevel(Double batteryLevel) {
		this.batteryLevel = batteryLevel;
	}

	public Double getRssiAverage() {
		return this.rssiAverage;
	}

	public void setRssiAverage(Double rssiAverage) {
		this.rssiAverage = rssiAverage;
	}

	public Double getRssiStd() {
		return this.rssiStd;
	}

	public void setRssiStd(Double rssiStd) {
		this.rssiStd = rssiStd;
	}

	public Double getLqiAverage() {
		return this.lqiAverage;
	}

	public void setLqiAverage(Double lqiAverage) {
		this.lqiAverage = lqiAverage;
	}

	public Double getLqiStd() {
		return this.lqiStd;
	}

	public void setLqiStd(Double lqiStd) {
		this.lqiStd = lqiStd;
	}

}
