package com.karrus.demo.shared.hibernate;
// Generated 14 janv. 2020 17:44:50 by Hibernate Tools 5.4.7.Final

/**
 * Feature generated by hbm2java
 */
public class Feature implements java.io.Serializable {

	private String feature;
	private Boolean enabled;

	public Feature() {
	}

	public Feature(String feature) {
		this.feature = feature;
	}

	public Feature(String feature, Boolean enabled) {
		this.feature = feature;
		this.enabled = enabled;
	}

	public String getFeature() {
		return this.feature;
	}

	public void setFeature(String feature) {
		this.feature = feature;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

}
