package com.karrus.demo.shared.hibernate;
// Generated 14 janv. 2020 17:30:47 by Hibernate Tools 5.4.7.Final

/**
 * GeographyColumns generated by hbm2java
 */
public class GeographyColumns implements java.io.Serializable {

	private GeographyColumnsId id;

	public GeographyColumns() {
	}

	public GeographyColumns(GeographyColumnsId id) {
		this.id = id;
	}

	public GeographyColumnsId getId() {
		return this.id;
	}

	public void setId(GeographyColumnsId id) {
		this.id = id;
	}

}
