package com.karrus.demo.shared.hibernate;
// Generated 14 janv. 2020 17:30:47 by Hibernate Tools 5.4.7.Final

/**
 * GeometryColumns generated by hbm2java
 */
public class GeometryColumns implements java.io.Serializable {

	private GeometryColumnsId id;

	public GeometryColumns() {
	}

	public GeometryColumns(GeometryColumnsId id) {
		this.id = id;
	}

	public GeometryColumnsId getId() {
		return this.id;
	}

	public void setId(GeometryColumnsId id) {
		this.id = id;
	}

}
