package com.karrus.demo.shared.hibernate;
// Generated 14 janv. 2020 17:44:50 by Hibernate Tools 5.4.7.Final

/**
 * Itinerary generated by hbm2java
 */
public class Itinerary implements java.io.Serializable {

	private ItineraryId id;
	private String name;
	private Integer nominalTravelTime;
	private Integer maxTravelTime;
	private Integer levelOfServiceThreshold1;
	private Integer levelOfServiceThreshold2;

	public Itinerary() {
	}

	public Itinerary(ItineraryId id) {
		this.id = id;
	}

	public Itinerary(ItineraryId id, String name, Integer nominalTravelTime, Integer maxTravelTime,
			Integer levelOfServiceThreshold1, Integer levelOfServiceThreshold2) {
		this.id = id;
		this.name = name;
		this.nominalTravelTime = nominalTravelTime;
		this.maxTravelTime = maxTravelTime;
		this.levelOfServiceThreshold1 = levelOfServiceThreshold1;
		this.levelOfServiceThreshold2 = levelOfServiceThreshold2;
	}

	public ItineraryId getId() {
		return this.id;
	}

	public void setId(ItineraryId id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getNominalTravelTime() {
		return this.nominalTravelTime;
	}

	public void setNominalTravelTime(Integer nominalTravelTime) {
		this.nominalTravelTime = nominalTravelTime;
	}

	public Integer getMaxTravelTime() {
		return this.maxTravelTime;
	}

	public void setMaxTravelTime(Integer maxTravelTime) {
		this.maxTravelTime = maxTravelTime;
	}

	public Integer getLevelOfServiceThreshold1() {
		return this.levelOfServiceThreshold1;
	}

	public void setLevelOfServiceThreshold1(Integer levelOfServiceThreshold1) {
		this.levelOfServiceThreshold1 = levelOfServiceThreshold1;
	}

	public Integer getLevelOfServiceThreshold2() {
		return this.levelOfServiceThreshold2;
	}

	public void setLevelOfServiceThreshold2(Integer levelOfServiceThreshold2) {
		this.levelOfServiceThreshold2 = levelOfServiceThreshold2;
	}

}
