package com.karrus.demo.shared.hibernate;
// Generated 14 janv. 2020 17:44:50 by Hibernate Tools 5.4.7.Final

/**
 * LfFonction generated by hbm2java
 */
public class LfFonction implements java.io.Serializable {

	private LfFonctionId id;
	private String htmlPopup;

	public LfFonction() {
	}

	public LfFonction(LfFonctionId id) {
		this.id = id;
	}

	public LfFonction(LfFonctionId id, String htmlPopup) {
		this.id = id;
		this.htmlPopup = htmlPopup;
	}

	public LfFonctionId getId() {
		return this.id;
	}

	public void setId(LfFonctionId id) {
		this.id = id;
	}

	public String getHtmlPopup() {
		return this.htmlPopup;
	}

	public void setHtmlPopup(String htmlPopup) {
		this.htmlPopup = htmlPopup;
	}

}
