package com.karrus.demo.shared.hibernate;
// Generated 14 janv. 2020 17:30:47 by Hibernate Tools 5.4.7.Final

/**
 * LfPolylineId generated by hbm2java
 */
public class LfPolylineId implements java.io.Serializable {

	private String originDest;
	private String zoomLevel;

	public LfPolylineId() {
	}

	public LfPolylineId(String originDest, String zoomLevel) {
		this.originDest = originDest;
		this.zoomLevel = zoomLevel;
	}

	public String getOriginDest() {
		return this.originDest;
	}

	public void setOriginDest(String originDest) {
		this.originDest = originDest;
	}

	public String getZoomLevel() {
		return this.zoomLevel;
	}

	public void setZoomLevel(String zoomLevel) {
		this.zoomLevel = zoomLevel;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LfPolylineId))
			return false;
		LfPolylineId castOther = (LfPolylineId) other;

		return ((this.getOriginDest() == castOther.getOriginDest()) || (this.getOriginDest() != null
				&& castOther.getOriginDest() != null && this.getOriginDest().equals(castOther.getOriginDest())))
				&& ((this.getZoomLevel() == castOther.getZoomLevel()) || (this.getZoomLevel() != null
						&& castOther.getZoomLevel() != null && this.getZoomLevel().equals(castOther.getZoomLevel())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOriginDest() == null ? 0 : this.getOriginDest().hashCode());
		result = 37 * result + (getZoomLevel() == null ? 0 : this.getZoomLevel().hashCode());
		return result;
	}

}
