package com.karrus.demo.shared.hibernate;
// Generated 14 janv. 2020 17:30:47 by Hibernate Tools 5.4.7.Final

/**
 * LfPolyline generated by hbm2java
 */
public class LfPolyline implements java.io.Serializable {

	private LfPolylineId id;
	private String listOfLatlngs;
	private String color;

	public LfPolyline() {
	}

	public LfPolyline(LfPolylineId id, String listOfLatlngs) {
		this.id = id;
		this.listOfLatlngs = listOfLatlngs;
	}

	public LfPolyline(LfPolylineId id, String listOfLatlngs, String color) {
		this.id = id;
		this.listOfLatlngs = listOfLatlngs;
		this.color = color;
	}

	public LfPolylineId getId() {
		return this.id;
	}

	public void setId(LfPolylineId id) {
		this.id = id;
	}

	public String getListOfLatlngs() {
		return this.listOfLatlngs;
	}

	public void setListOfLatlngs(String listOfLatlngs) {
		this.listOfLatlngs = listOfLatlngs;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

}
