package com.karrus.demo.shared.hibernate;
// Generated 14 janv. 2020 17:44:50 by Hibernate Tools 5.4.7.Final

/**
 * SsyItinerary generated by hbm2java
 */
public class SsyItinerary implements java.io.Serializable {

	private String name;
	private Integer ssyId;
	private Integer minValidTt;
	private Integer maxFreeflowTt;

	public SsyItinerary() {
	}

	public SsyItinerary(String name) {
		this.name = name;
	}

	public SsyItinerary(String name, Integer ssyId, Integer minValidTt, Integer maxFreeflowTt) {
		this.name = name;
		this.ssyId = ssyId;
		this.minValidTt = minValidTt;
		this.maxFreeflowTt = maxFreeflowTt;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getSsyId() {
		return this.ssyId;
	}

	public void setSsyId(Integer ssyId) {
		this.ssyId = ssyId;
	}

	public Integer getMinValidTt() {
		return this.minValidTt;
	}

	public void setMinValidTt(Integer minValidTt) {
		this.minValidTt = minValidTt;
	}

	public Integer getMaxFreeflowTt() {
		return this.maxFreeflowTt;
	}

	public void setMaxFreeflowTt(Integer maxFreeflowTt) {
		this.maxFreeflowTt = maxFreeflowTt;
	}

}
