package com.karrus.demo.shared.hibernate;
// Generated 14 janv. 2020 17:44:50 by Hibernate Tools 5.4.7.Final

/**
 * Station generated by hbm2java
 */
public class Station implements java.io.Serializable {

	private String station;
	private String serial;
	private String hostPptp;
	private String lanes;
	private String mags;
	private String rps;
	private Double longitude;
	private Double latitude;

	public Station() {
	}

	public Station(String station, String serial, String hostPptp, String lanes) {
		this.station = station;
		this.serial = serial;
		this.hostPptp = hostPptp;
		this.lanes = lanes;
	}

	public Station(String station, String serial, String hostPptp, String lanes, String mags, String rps,
			Double longitude, Double latitude) {
		this.station = station;
		this.serial = serial;
		this.hostPptp = hostPptp;
		this.lanes = lanes;
		this.mags = mags;
		this.rps = rps;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	public String getStation() {
		return this.station;
	}

	public void setStation(String station) {
		this.station = station;
	}

	public String getSerial() {
		return this.serial;
	}

	public void setSerial(String serial) {
		this.serial = serial;
	}

	public String getHostPptp() {
		return this.hostPptp;
	}

	public void setHostPptp(String hostPptp) {
		this.hostPptp = hostPptp;
	}

	public String getLanes() {
		return this.lanes;
	}

	public void setLanes(String lanes) {
		this.lanes = lanes;
	}

	public String getMags() {
		return this.mags;
	}

	public void setMags(String mags) {
		this.mags = mags;
	}

	public String getRps() {
		return this.rps;
	}

	public void setRps(String rps) {
		this.rps = rps;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

}
