package com.karrus.demo.shared.hibernate;
// Generated 14 janv. 2020 17:44:50 by Hibernate Tools 5.4.7.Final

/**
 * Synoptic generated by hbm2java
 */
public class Synoptic implements java.io.Serializable {

	private String stationLabel;
	private Integer XPosition;
	private Integer YPosition;

	public Synoptic() {
	}

	public Synoptic(String stationLabel) {
		this.stationLabel = stationLabel;
	}

	public Synoptic(String stationLabel, Integer XPosition, Integer YPosition) {
		this.stationLabel = stationLabel;
		this.XPosition = XPosition;
		this.YPosition = YPosition;
	}

	public String getStationLabel() {
		return this.stationLabel;
	}

	public void setStationLabel(String stationLabel) {
		this.stationLabel = stationLabel;
	}

	public Integer getXPosition() {
		return this.XPosition;
	}

	public void setXPosition(Integer XPosition) {
		this.XPosition = XPosition;
	}

	public Integer getYPosition() {
		return this.YPosition;
	}

	public void setYPosition(Integer YPosition) {
		this.YPosition = YPosition;
	}

}
