package com.karrus.demo.shared.hibernate;
// Generated 14 janv. 2020 17:44:50 by Hibernate Tools 5.4.7.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String login;
	private String password;
	private String name;
	private String email;
	private String group;

	public User() {
	}

	public User(String login, String group) {
		this.login = login;
		this.group = group;
	}

	public User(String login, String password, String name, String email, String group) {
		this.login = login;
		this.password = password;
		this.name = name;
		this.email = email;
		this.group = group;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGroup() {
		return this.group;
	}

	public void setGroup(String group) {
		this.group = group;
	}

}
